#!/bin/bash
# Generates services/GeneratedTheme.qml from Omarchy's active theme.
# Called by Omarchy hooks (theme-set, font-set) or manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$REPO_DIR/services/GeneratedTheme.qml"

COLORS_FILE="$HOME/.config/omarchy/current/theme/colors.toml"
WAYBAR_CSS="$HOME/.config/waybar/style.css"

# --- Read colours from colors.toml ---
declare -A colors
if [[ -f "$COLORS_FILE" ]]; then
    while IFS='=' read -r key value; do
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs | tr -d '"')
        [[ -n "$key" && -n "$value" ]] && colors["$key"]="$value"
    done < "$COLORS_FILE"
fi

# --- Read font from Waybar CSS (same method as omarchy font current) ---
font_family="CaskaydiaMono Nerd Font Mono"
if [[ -f "$WAYBAR_CSS" ]]; then
    detected=$(grep -oP "font-family:\s*[\"']?\K[^;\"']+" "$WAYBAR_CSS" | head -n1)
    [[ -n "$detected" ]] && font_family="$detected"
fi

# --- Helper: get colour with fallback ---
get_color() {
    local key="$1"
    local fallback="$2"
    echo "${colors[$key]:-$fallback}"
}

# --- Generate QML ---
cat > "$OUTPUT" << QMLEOF
// Auto-generated by scripts/generate-theme.sh — do not edit manually
pragma Singleton

import QtQuick

QtObject {
    readonly property color background: "$(get_color background '#060B1E')"
    readonly property color foreground: "$(get_color foreground '#ffcead')"
    readonly property color accent: "$(get_color accent '#7d82d9')"

    readonly property color color0: "$(get_color color0 '#3C486D')"
    readonly property color color1: "$(get_color color1 '#ED5B5A')"
    readonly property color color2: "$(get_color color2 '#92a593')"
    readonly property color color3: "$(get_color color3 '#E9BB4F')"
    readonly property color color4: "$(get_color color4 '#7d82d9')"
    readonly property color color5: "$(get_color color5 '#c89dc1')"
    readonly property color color6: "$(get_color color6 '#a3bfd1')"
    readonly property color color7: "$(get_color color7 '#F99957')"
    readonly property color color8: "$(get_color color8 '#6d7db6')"
    readonly property color color9: "$(get_color color9 '#faaaa9')"
    readonly property color color10: "$(get_color color10 '#c4cfc4')"
    readonly property color color11: "$(get_color color11 '#f7dc9c')"
    readonly property color color12: "$(get_color color12 '#c2c4f0')"
    readonly property color color13: "$(get_color color13 '#ead7e7')"
    readonly property color color14: "$(get_color color14 '#dfeaf0')"
    readonly property color color15: "$(get_color color15 '#ffcead')"

    readonly property string fontFamily: "$font_family"
    readonly property int fontSize: 12
}
QMLEOF

echo "Generated $OUTPUT"
